version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    stdin_open: true
    tty: true

  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    stdin_open: true
    tty: true

